package DSA_Assignment2_Q1;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eirik
 */
public class Panel extends javax.swing.JPanel {

    private final Controller controller;
    private final Model model;
    private String selectedList;

    /**
     * Creates new form Panel
     */
    public Panel() {
        this.controller = new Controller(this);
        this.model = new Model();
        this.selectedList = SortOption.NAME.nameOfKey; // default value
        initComponents();
        addListeners();
    }

    private void addListeners() {
        loadButton.addActionListener(controller);
        saveButton.addActionListener(controller);
        keyButton.addActionListener(controller);
        sortButton.addActionListener(controller);
        searchButton.addActionListener(controller);
    }

    public void loadFile() {
        JFileChooser chooser = new JFileChooser(new File("./res"));
        chooser.setFileFilter(new FileNameExtensionFilter("Text File (\".txt\")", "txt"));
        int option = chooser.showOpenDialog(null);

        // if user chooses a file
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                setStudentsText(model.readFile(chooser.getSelectedFile()));
            } catch (FileNotFoundException ex) {
                System.out.println("Error: " + ex.toString());
            }
        }
    }

    public void saveFile() {
        JFileChooser chooser = new JFileChooser(new File("./res"));
        chooser.setFileFilter(new FileNameExtensionFilter("Text File (\".txt\")", "txt"));
        int option = chooser.showSaveDialog(null);

        if (option == JFileChooser.APPROVE_OPTION) {
            String fileName = chooser.getSelectedFile().getPath();
            model.writeFile(studentsText.getText(), fileName);
        }
    }

    private void setStudentsText(String str) {
        this.studentsText.setText(str);
    }

    public void setKey() {
        String[] sortOptions = new String[SortOption.NUMBER_OF_OPTIONS];
        sortOptions[0] = SortOption.NAME.nameOfKey;
        sortOptions[1] = SortOption.MARK.nameOfKey;

        selectedList = (String) JOptionPane.showInputDialog(null, "Sort Options", "Sort Options", JOptionPane.PLAIN_MESSAGE, null, sortOptions, null);

        if (selectedList != null) {
            setStudentsText(model.getSelectedList(selectedList));
        }
    }

    public void sort() {
        model.sort();
        setStudentsText(model.getSelectedList(selectedList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        keyButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        studentsTextScrollPane = new javax.swing.JScrollPane();
        studentsText = new javax.swing.JTextArea();
        sortButton = new javax.swing.JButton();

        loadButton.setText("Load");

        saveButton.setText("Save");

        keyButton.setText("Set Key");

        searchButton.setText("Search");

        studentsTextScrollPane.setViewportView(null);

        studentsText.setColumns(20);
        studentsText.setRows(5);
        studentsTextScrollPane.setViewportView(studentsText);

        sortButton.setText("Sort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentsTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keyButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(saveButton)
                    .addComponent(keyButton)
                    .addComponent(sortButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentsTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton keyButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton sortButton;
    private javax.swing.JTextArea studentsText;
    private javax.swing.JScrollPane studentsTextScrollPane;
    // End of variables declaration//GEN-END:variables
}
